version: "3.8"

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"

  database:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5600:5432"

volumes:
  postgres_data:
