"""add login field to users table

Revision ID: 46499c4818d7
Revises: 81cd4caab28e
Create Date: 2022-07-17 01:38:42.259809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46499c4818d7'
down_revision = '81cd4caab28e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
