"""added product details columns

Revision ID: 00fa696d08ae
Revises: ffe6a249e9e8
Create Date: 2022-08-03 17:48:22.462725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fa696d08ae'
down_revision = 'ffe6a249e9e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('by_prescription', sa.Boolean(), nullable=False, default=False))
    op.add_column('products', sa.Column('expiration', sa.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('storage_conditions', sa.String(), nullable=True))
    op.add_column('products', sa.Column('color_taste_aroma', sa.String(), nullable=True))
    op.add_column('products', sa.Column('indications_for_use', sa.String(), nullable=True))
    op.add_column('products', sa.Column('contraindications', sa.String(), nullable=True))
    op.add_column('products', sa.Column('pharmacological_effect', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'pharmacological_effect')
    op.drop_column('products', 'contraindications')
    op.drop_column('products', 'indications_for_use')
    op.drop_column('products', 'color_taste_aroma')
    op.drop_column('products', 'storage_conditions')
    op.drop_column('products', 'expiration')
    op.drop_column('products', 'by_prescription')
    # ### end Alembic commands ###
